### ISSUE TITLE
Exception executing the class 'com.jom._OPERATOR_MULTIPLY'

### ISSUE THREAD

**Issue by mahdi7** [girtel/JOM#15]
While running an optimization algorithm through Net2Plan, algorithm execution is stopped by an exception caused by "_GC overhead limit exceeded_", originated from **com.jom._OPERATOR_MULTIPLY**:

```
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at com.jom._INTERNAL_ExpressionParser.evaluate(_INTERNAL_ExpressionParser.java:404)
        at com.jom._INTERNAL_ExpressionParser.evaluate(_INTERNAL_ExpressionParser.java:25)
        at com.jom.javaluator.AbstractEvaluator.output(AbstractEvaluator.java:421)
        at com.jom.javaluator.AbstractEvaluator.evaluate(AbstractEvaluator.java:212)
        at com.jom._INTERNAL_ExpressionParser.evaluate(_INTERNAL_ExpressionParser.java:165)
        at com.jom._INTERNAL_ConstraintArray.<init>(_INTERNAL_ConstraintArray.java:47)
        at com.jom.OptimizationProblem.addConstraint(OptimizationProblem.java:127)
        at com.jom.OptimizationProblem.addConstraint(OptimizationProblem.java:108)
        at MY_ALGORITHM.executeAlgorithm(MY_ALGORITHM.java:315)
        at com.net2plan.cli.plugins.CLINetworkDesign.executeFromCommandLine(CLINetworkDesign.java:158)
        at com.net2plan.cli.CLINet2Plan.<init>(CLINet2Plan.java:95)
        at com.net2plan.cli.CLINet2Plan.main(CLINet2Plan.java:212)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
        at cern.colt.matrix.tint.impl.DenseIntMatrix2D.like1D(DenseIntMatrix2D.java:1784)
        at cern.colt.matrix.tint.IntMatrix2D.viewRow(IntMatrix2D.java:1702)
        at com.jom.DoubleMatrixND.ind2sub(DoubleMatrixND.java:235)
        at com.jom._INTERNAL_AffineExpressionCoefs.operator_multiply(_INTERNAL_AffineExpressionCoefs.java:127)
        at com.jom._OPERATOR_MULTIPLY.<init>(_OPERATOR_MULTIPLY.java:54)

```

**Comment by ppavon** [comment]
No real info here to see what's happening. This seems a limitation from your memory (maybe the problem is too large?)
